spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  jackson:
    serialization:
      write_dates_as_timestamps: false
